### ISSUE TITLE
Improve my portfolio.  (Animations, Transitions and other styles) 

### ISSUE THREAD

**Issue by kd1729** [onlykingKD/portfolio#11]

**Comment by SGI-CAPP-AT2** [comment]
assign to me

**Comment by SGI-CAPP-AT2** [comment]
@onlykingKD 
Check #22 .

**Comment by onlykingKD** [comment]
![Screenshot_20211010-153935.png](https://user-images.githubusercontent.com/55577276/136691391-3af1ea79-fd82-4063-b7b5-0ee130c87f00.png)

**Comment by onlykingKD** [comment]
![Screenshot_20211010-153927.png](https://user-images.githubusercontent.com/55577276/136691411-00dfda4e-d92a-498b-9fe8-6d693348c326.png)

**Comment by onlykingKD** [comment]
It was looking so bad in desktop mode. Whole styling gone.
You want hacktoberfest label make a dummy PR, I will merge.

> @onlykingKD
> 
> Why you reverted my pr #24 #22 ?

**Comment by SGI-CAPP-AT2** [comment]
Sorry,
But it's working on my desktop .
Check it again
