### ISSUE TITLE
Improve Color Combination

### ISSUE THREAD

**Issue by onlykingKD** [onlykingKD/portfolio#2]
Need help in improving color combination.

**Comment by HiruniPerera** [comment]
Hi I would love to contribute to your project and help you with improving color combination, please assign this task to me :)

**Comment by onlykingKD** [comment]
Yup go ahead 😊

**Comment by therohit777** [comment]
I want to Contribute , assign me this issue

**Comment by onlykingKD** [comment]
@therohit777 try to improve the color combination, I need a dark mode

**Comment by therohit777** [comment]
ok

**Comment by therohit777** [comment]
@onlykingKD Changes have been added check this out. modified by therohit777 #6

**Comment by onlykingKD** [comment]
> 
> 
> @onlykingKD Changes have been added check this out. modified by therohit777 #6

Its not that good but np I am merging it
