### ISSUE TITLE
Instagram link is not working

### ISSUE THREAD

**Issue by Himanshu664** [onlykingKD/portfolio#30]
Instagram link is not working in footer section,link is broken.
<img width="925" alt="Screenshot 2021-10-11 161657" src="https://user-images.githubusercontent.com/76220055/136778168-adea2adb-57a3-4159-8fe8-e629002ce640.png">

**Comment by Himanshu664** [comment]
@onlykingKD I want to work on this issue please provide correct instagram user name

**Comment by onlykingKD** [comment]
I disabled my instagram id, thats why not working.

> @onlykingKD I want to work on this issue please provide correct instagram user name
