### ISSUE TITLE
Addition of new section

### ISSUE THREAD

**Issue by kd1729** [onlykingKD/portfolio#34]
Add an Extra Section of **My Gallup Strengths** between About Me Section and My Skills Section.

All the 5 strengths should be in a single row like My skills section.

- Please include a screenshot while submitting the PR.

[Drive Link of My Gallup Strengths](https://drive.google.com/file/d/1Sn4WLPqfAd9G5B-aijhpBEWbTxYiVOUi/view?usp=sharing)

**Comment by aman-netizen** [comment]
Hi @onlykingKD I want to work on this issue can you please assign me this if it not done.

**Comment by onlykingKD** [comment]
> Hi @onlykingKD I want to work on this issue can you please assign me this if it not done.

yes go ahead.

**Comment by onlykingKD** [comment]
Please submit the PR by today itself.

> Hi @onlykingKD I want to work on this issue can you please assign me this if it not done.

**Comment by aman-netizen** [comment]
> Please submit the PR by today itself.
> 
> > Hi @onlykingKD I want to work on this issue can you please assign me this if it not done.

Ok
