### ISSUE TITLE
Navbar in Mobile View

### ISSUE THREAD

**Issue by MRIDUL-MB** [onlykingKD/portfolio#47]
Navbar is messy in mobile view, check the ss below
![image](https://user-images.githubusercontent.com/53037689/137761254-a1d9ea72-8ce5-48ae-ba0f-5e977ce63e23.png)

**Comment by onlykingKD** [comment]
Yes , work on it.
Try to make it responsive, like hamburger navbar,

**Comment by MRIDUL-MB** [comment]
label this issue as hacktoberfest
